language: cpp
dist: bionic

addons:
  apt:
    packages: libgtest-dev binutils-arm-none-eabi gcc-arm-none-eabi libstdc++-arm-none-eabi-newlib libnewlib-arm-none-eabi

env:
  - RUN_TESTS=true OPTIONS=

cache:
  directories:
    - toolchain

install:
  - if [ $RUN_TESTS != "true" ]; then ./getToolchain.sh; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..  $OPTIONS

script: 
  - make
  - if [ $RUN_TESTS == "true" ]; then make test; fi
