language: cpp

env:
  - RUN_TESTS=true OPTIONS=

cache:
  directories:
    - toolchain

install:
  - if [ $RUN_TESTS != "true" ]; then ./getToolchain.sh; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..  $OPTIONS

script: 
  - make
  - if [ $RUN_TESTS == "true" ]; then make test; fi
